version: 0.0.{build}
branches:
  only:
  - master
image: Ubuntu
environment:
  MINIKUBE_VERSION: "1.0.0"
  KUBECTL_VERSION: "1.14.1"
  # Changes ownership of minikube config dirs to running user
  CHANGE_MINIKUBE_NONE_USER: "true"
  # Set kubeconfig and minikube paths
  KUBECONFIG: "/home/appveyor/.kube/config"
  MINIKUBE_HOME: "/home/appveyor/kubernetes"
  # Disable prompts for CI
  MINIKUBE_WANTUPDATENOTIFICATION: "false"
  MINIKUBE_WANTREPORTERRORPROMPT: "false"
  APPVEYOR_SSH_BLOCK: true
  APPVEYOR_SSH_KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCmgZMwyHhjf+VteXZ9yVDNPjttoXwY9guLrknAsoQAAOKyMkLck3HgrT/ZARg/hmDAlEIxG504Xb6wBGJpLjxWA0WlSBuk86I9ejnnsEUOu9zSZHXXYYsoR7lhIdOP05Ifs8aYCpONYZkWSzee9cwZlLehHPwLXzM6FcJbaYoXZlGLuxzg3J5MY5MPnFi6uj3h0lJRIfbclU15RT3fNIp9olOUg8WpzqYJWNdv9AZQvF9z+WugVUw9grGrpXbOH7iK+FFN1IgTdiLYrh1SHOi9fGLA4BrOYcyclAvuFryy4t2Wu6wFcm1rZR5sCsEbXRYB3ZheiHeVJd3QWGDjser1u7A5kv391iyiOQSvQBkNWt1t6LYnH5fOL5+6vZMAGm/od7+M8F4ozpeA79opXcn8pHbK9uH8Dw2+/vgJ1BfiL32OCbn/Fby/hyxfwnT6SBllwz2UcNBx6tzCCZAXjugPr2kUvpE100a9Xc7czLOk7KIjznV5gKHnjGP+27q6SDIwN58sSw0R//MqbavhXeenLe/eZ7HU0/l/q6jCdcq2Vay1pyNI+Uga1PuKH/BO8bMseWr0/1Z5TMt3z0lFwCTHBjtgPOj8VCgV8oBOza1+5rxw0rdWrsuBACmJFzduhldCYK4M5gYehb4ZAJyg7U2XL/FuDD8fcw+5dO+Z1YLW3w== openpgp:0x0A2ADCAF"
services:
 - docker
install:
- sh: |
    curl -Lo minikube https://storage.googleapis.com/minikube/releases/v${MINIKUBE_VERSION}/minikube-linux-amd64
    chmod +x minikube
    sudo mv minikube /usr/local/bin/.
- sh: |
    curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
    chmod +x kubectl
    sudo mv kubectl /usr/local/bin/.
build_script:
- sh: |
    
    sudo -E minikube start --vm-driver=none
    kubectl describe node minikube
    kubectl apply -f ./api.yaml

    ./wait_pod_is_ready.sh 60 1
 #   curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
